#!/usr/bin/env python3

import pandas as pd
import numpy as np
import pickle
import geopandas as gpd
import matplotlib.pyplot as plt   
from mpl_toolkits.basemap import Basemap

# set figure font to Arial
import matplotlib as mpl
mpl.rc('font',family='Arial')

'''
all datasets for this code can be downloaded from Zenodo.org (see README for details).
'''

# open dataframe of lightning-caused fires and MRMS precipitation amounts
infile = open("all_matched2.pkl",'rb')
all_matched = pickle.load(infile)
infile.close()

# open shapefile of ecoprovinces as Geodataframe
ecoprovinces = gpd.read_file('western_ecoprovinces.shp')

eco_counts = all_matched.groupby('ecoprov').agg('count') # count fires in each ecoprovince
eco_precs = all_matched.groupby('ecoprov').agg('median') # get median precipitation amount in each ecoprovince

eco_counts1 = list(eco_counts.lat)
eco_counts1.insert(2,0) # handle ecoprovince with no lightning-caused fires
eco_counts1.insert(4,0) # handle ecoprovince with no lightning-caused fires
ecoprovinces['nfires'] = eco_counts1 # add fire count to geodataframe
eco_precs1 = list(eco_precs.prec)
eco_precs1.insert(2,0) # handle ecoprovince with no lightning-caused fires
eco_precs1.insert(4,0) # handle ecoprovince with no lightning-caused fires
ecoprovinces['prec'] = eco_precs1 # add precip amounts to geodataframe

# import shapefile of US states, and subset to western US
states = gpd.read_file('cb_2018_us_state_5m.shp')
states = states.to_crs("EPSG:4326")
states = states[states.NAME.isin(['Washington','Oregon','Idaho','Montana',
                                  'California','Nevada','Utah','Wyoming',
                                  'Colorado','Arizona','New Mexico'])]

# plot Figure 1a - number of matched fires in each ecoprovince
ecoplot = ecoprovinces.plot(column='nfires', legend=True, cmap=plt.cm.get_cmap('YlOrRd',8), 
                            edgecolor='k', vmin = 0, vmax = 800)
ecoplot.axis('off')
states.boundary.plot(ax=ecoplot, edgecolor='k', lw=1)
plt.title('Number of fires matched to \n lightning in each ecoprovince', size=17)
fig = ecoplot.figure
cb_ax = fig.axes[1]
cb_ax.tick_params(labelsize=15)

# Figure 2b - making map of percentage of LIWs that were promptly detected

# these percentages were calculated from the "all_matched2.pkl" dataframe
perc = np.array([94.4,78.7,np.nan,np.nan,np.nan,89.5,86.3,91.6,95.0,
                 79.1,np.nan,80.7,77.6,np.nan,82.7,70.4])
ecoprovinces['percentage'] = perc

ecoplot = ecoprovinces.plot(column='percentage', legend=True, cmap=plt.cm.get_cmap('YlOrRd',6), 
                            edgecolor='k', missing_kwds = dict(color = "0.5"), 
                            vmin=70, vmax=100, 
                            legend_kwds = dict(ticks = np.arange(70,100.01,5)))
ecoplot.axis('off')
states.boundary.plot(ax=ecoplot, edgecolor='k', lw=1)
plt.title('Percentage of LIWs that \n were promptly-detected', size=17)
fig = ecoplot.figure
cb_ax = fig.axes[1]
cb_ax.tick_params(labelsize=15)

# note - Figure 1C was made using QGIS

